INFOMAX/Controllers/AdminDashController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using INFOMAX.DB_Context;
using System.IO;
using INFOMAX.Models;
using System.Configuration;

namespace INFOMAX.Controllers
{
    public class AdminDashController : Controller
    {

        infomaxEntities con = new infomaxEntities();
        string strConString = "Data Source=.;Initial Catalog=Infomax;Integrated Security=True";
        // GET: AdminDash
        public ActionResult AdminHome()
        {
            GetName();
                Count();

            return View();
        }
        public void GetName()
        {
            Connection conn = new Connection();
            conn.getData("select * from login where Email='"+ Session["UserName"].ToString() + "'" );
            ViewBag.User = conn.dt.Rows[0]["Name"].ToString();
        }
        [HttpGet]
        public ActionResult UploadSliderImage()
        {
            GetName();
            Count();
            List<Models.CarouselSlider> sliderimages = new List<Models.CarouselSlider>();
            //string CS = ConfigurationManager.ConnectionStrings["infomaxEntities"].ConnectionString;
            using (SqlConnection con = new SqlConnection(strConString))
            {
                SqlCommand cmd = new SqlCommand("spGetAllSliderImage", con);
                cmd.CommandType = CommandType.StoredProcedure;
                con.Open();
                SqlDataReader rdr = cmd.ExecuteReader();
                while (rdr.Read())
                {
                    Models.CarouselSlider slider = new Models.CarouselSlider();
                    slider.ID = Convert.ToInt32(rdr["ID"]);
                    slider.Name = rdr["Name"].ToString();
                    slider.FileSize = Convert.ToInt32(rdr["FileSize"]);
                    slider.FilePath = rdr["FilePath"].ToString();

                    sliderimages.Add(slider);
                }
            }
            return View(sliderimages);
        }
        [HttpPost]
        public ActionResult UploadSliderImage(HttpPostedFileBase fileupload)
        {
            if (fileupload != null)
            {
                string fileName = Path.GetFileName(fileupload.FileName);
                int fileSize = fileupload.ContentLength;
                int Size = fileSize / 1000;
                fileupload.SaveAs(Server.MapPath("~/SliderImages/" + fileName));

                // string CS = ConfigurationManager.ConnectionStrings["infomaxEntities"].ConnectionString;
                using (SqlConnection con = new SqlConnection(strConString))
                {
                    SqlCommand cmd = new SqlCommand("spAddNewSliderImage", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    con.Open();
                    cmd.Parameters.AddWithValue("@Name", fileName);
                    cmd.Parameters.AddWithValue("@FileSize", Size);
                    cmd.Parameters.AddWithValue("FilePath", "~/SliderImages/" + fileName);
                    cmd.ExecuteNonQuery();
                }
            }
            return RedirectToAction("UploadSliderImage");
        }
        public ActionResult Delete(int id)
        {
            SqlConnection con = new SqlConnection(strConString);
            SqlCommand cmd = new SqlCommand("delete from CarouselSlider where ID=" + id, con);
            con.Open();
            int i = cmd.ExecuteNonQuery();
            con.Close();

            return RedirectToAction("UploadSliderImage");
        }
        public ActionResult Products()
        {
            GetName();
            Count();
            return View();
        }
        [HttpPost]
        public ActionResult Products(HttpPostedFileBase fileupload, ProductModel objPro)
        {

            if (fileupload != null)
            {
                string fileName = Path.GetFileName(fileupload.FileName);
                int fileSize = fileupload.ContentLength;
                int Size = fileSize / 1000;
                fileupload.SaveAs(Server.MapPath("~/Products/" + fileName));

                // string CS = ConfigurationManager.ConnectionStrings["infomaxEntities"].ConnectionString;
                using (SqlConnection con = new SqlConnection(strConString))
                {
                    SqlCommand cmd = new SqlCommand("insert into Products values(@P_Name,@FileSize,@file,@P_Desc,@p_Features,@P_Price)", con);
                    cmd.CommandType = CommandType.Text;
                    con.Open();
                    cmd.Parameters.AddWithValue("@P_Name", objPro.Product);
                    cmd.Parameters.AddWithValue("@FileSize", Size);
                    cmd.Parameters.AddWithValue("@file", "~/Products/" + fileName);
                    cmd.Parameters.AddWithValue("@P_Desc", objPro.Desc);
                    cmd.Parameters.AddWithValue("@p_Features", objPro.Features);
                    cmd.Parameters.AddWithValue("@P_Price", objPro.Price);
                    int i = cmd.ExecuteNonQuery();
                    con.Close();
                    ModelState.Clear();
                    if (i == 1)
                    {
                        ViewBag.Message = "Product Successfully Added";
                    }
                    else
                    {
                        ViewBag.Message = "Failed";
                    }
                }

            }
            return View();
        }
        public ActionResult ManageProducts()
        {
            GetName();
            Count();
            ManageProductModel model = new ManageProductModel();
            DataTable dt = model.AllProducts();
            return View(dt);
        }
        public ActionResult EditProduct(int id)
        {
            ManageProductModel model = new ManageProductModel();
            DataTable dt = model.ProductById(id);
            return PartialView(dt);
            //return View(dt);
        }

        [HttpPost]
        public ActionResult UpdateProduct(HttpPostedFileBase fileupload, ManageProductModel mpm)
        {
            
            //string strConString = "Data Source=.;Initial Catalog=Infomax;Integrated Security=True";
            if (fileupload != null)
            {
                string fileName = Path.GetFileName(fileupload.FileName);
                int fileSize = fileupload.ContentLength;
                int Size = fileSize / 1000;
                fileupload.SaveAs(Server.MapPath("~/Products/" + fileName));
                SqlConnection conn = new SqlConnection("Data Source=.;Initial Catalog=Infomax;Integrated Security=True");
                // string CS = ConfigurationManager.ConnectionStrings["infomaxEntities"].ConnectionString;
                //{
                SqlCommand cmd = new SqlCommand("update Products set P_Name=@P_Name,FileSize=@FileSize,FilePath=@file,P_Desc=@P_Desc,p_Features=@p_Features,P_Price=@P_Price where P_ID=@P_ID", conn);
                cmd.CommandType = CommandType.Text;
                conn.Open();
                cmd.Parameters.AddWithValue("@P_ID", mpm.ID);
                cmd.Parameters.AddWithValue("@P_Name", mpm.Product);
                cmd.Parameters.AddWithValue("@FileSize", Size);
                cmd.Parameters.AddWithValue("@file", "~/Products/" + fileName);
                cmd.Parameters.AddWithValue("@P_Desc", mpm.Desc);
                cmd.Parameters.AddWithValue("@p_Features", mpm.Features);
                cmd.Parameters.AddWithValue("@P_Price", mpm.Price);
                int i = cmd.ExecuteNonQuery();
                conn.Close();
                ModelState.Clear();
                if (i == 1)
                {
                    ViewBag.Message = "Product Successfully Added";
                }
                else
                {
                    ViewBag.Message = "Failed";
                }
                //}
            }
            return RedirectToAction("ManageProducts");
        }
        public ActionResult DeleteProduct(int id)
        {
            SqlConnection con = new SqlConnection(strConString);
            SqlCommand cmd = new SqlCommand("delete from Products where P_ID=" + id, con);
            con.Open();
            int i = cmd.ExecuteNonQuery();
            con.Close();
            //if(i==1)
            //{
            //    ViewBag.Result = "Image Successfully Deleted";
            //}
            //else
            //{
            //    ViewBag.Result = "Can't Delete! Something went Wrong...";
            //}
            return RedirectToAction("ManageProducts");
        }
        public ActionResult Clients()
        {
            GetName();
            Count();
            List<Models.ClientModel> Objclient = new List<Models.ClientModel>();
            //string CS = ConfigurationManager.ConnectionStrings["infomaxEntities"].ConnectionString;
            using (SqlConnection con = new SqlConnection(strConString))
            {
                SqlCommand cmd = new SqlCommand("Select * from clients", con);
                cmd.CommandType = CommandType.Text;
                con.Open();
                SqlDataReader rdr = cmd.ExecuteReader();
                while (rdr.Read())
                {
                    Models.ClientModel client = new Models.ClientModel();
                    client.ID = Convert.ToInt32(rdr["ID"]);
                    client.Name = rdr["Name"].ToString();
                    //slider.FileSize = Convert.ToInt32(rdr["FileSize"]);
                    client.image = rdr["image"].ToString();

                    Objclient.Add(client);
                }
            }
            return View(Objclient);
        }
        [HttpPost]
        public ActionResult Clients(HttpPostedFileBase image, ClientModel cm)
        {
            if (image != null)
            {
                string fileName = Path.GetFileName(image.FileName);
                int fileSize = image.ContentLength;

INFOMAX/Views/AdminDash/AdminHome.cshtml
@{
    ViewBag.Title = "AdminHome";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>AdminHome</h2>

INFOMAX/Views/AdminDash/Clients.cshtml
@{
    ViewBag.Title = "UploadSliderImage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<script type="text/javascript">

    $(document).ready(function () {
        $("#dataTable").dataTable();
    });
</script>
@*<style>
        .carousel-inner img {
            width: 100%;
            height: 350px;
        }
    </style>*@

<body>
    <!-- BREADCRUMB-->
    <section class="au-breadcrumb m-t-75">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="au-breadcrumb-content">
                           <div class="au-breadcrumb-left">
                            
                            </div>
                         
                            <button class="au-btn au-btn-icon au-btn--green" data-toggle="modal" data-target="#myModal">
                                <i class="zmdi zmdi-plus"></i>add item
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END BREADCRUMB-->
    <div class="container py-4">
        <div class="card">
            <div class="card-header bg-primary text-white">
                @*<h6 class="text-uppercase">Image List</h6>*@
            </div>
            <div class="card-body">
                <div class="row">
                    <br /><br />
                    <button style="margin-left: 27px;margin-bottom:10px;" class="btn btn-primary rounded-0">
                        Client List
                    </button>
                    <div class="modal fade" id="myModal">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Upload New Slider Image</h4>
                                    <button type="button" class="close" data-dismiss="modal">×</button>
                                </div>
                                <div class="modal-body">
                                    @using (Html.BeginForm("Clients", "AdminDash", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div class="form-group">
                                            Client
                                            @*@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                            <div class="col-md-10">
                                                <input type="text" required name="Name" class="form-control" />
                                                @*@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })*@
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label>Choose File:</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file" id="fileupload" required name="image" style="color:black;" class="custom-file-input" />
                                                    <label class="custom-file-label"></label>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <input type="submit" id="btnUpload" class="btn btn-primary" value="Save" />
                                            @*<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>*@
                                        </div>

                                    }

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <table id="dataTable" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            @*<th>File Size(KB)</th>*@
                            <th>Images</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.ID</td>
                                <td>@item.Name</td>
                                @*<td>@item.FileSize</td>*@
                                <td>
                                    <img src="@Url.Content(@item.image)" alt="" width="80" height="60" class="img-thumbnail" />

                                </td>
                                <td>
                                    <a href="@Url.Action("DeleteClient", "AdminDash" , new { ID = @item.ID })" onclick="return confirm('Are you sure you wish to delete this Client?');"><i class='fas fa-trash-alt' style='font-size:20px;color:dodgerblue'></i></a>
                                    @*@Html.ActionLink("| Delete", "Delete", new { ID = @item.ID, @class = "fa fa-trash-o", @style = "font-size:48px;color:red" }, new { onclick = "return confirm('Are you sure you wish to delete this Slider Image?');" })*@
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>

INFOMAX/Views/AdminDash/EditProduct.cshtml
@using System.Data;
@using System.Data.SqlClient;
@model System.Data.DataTable
    

@{
    ViewBag.Title = "EditProduct";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="row" style="margin-left:30px;">
    @using (Html.BeginForm("UpdateProduct", "AdminDash", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <br /><br /><br />
        <div class="form-horizontal">
            <h4>Update Product</h4>
            <hr />
            <img src="@Url.Content(@Model.Rows[0]["FilePath"].ToString())" width="150" height="150"  style="margin-left:250px;" class="rounded" alt="..." class="w-100">
            <input name="ID" type="hidden" value="@Model.Rows[0]["P_ID"]" />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                Product
                <div class="col-md-10">
                    <input type="text" name="Product" value="@Model.Rows[0]["P_Name"]" />

                </div>
            </div>

            <div class="form-group">
                Choose File
                <div class="col-md-10">
                    <div class="custom-file">
                        <input type="file" id="fileupload" name="fileupload" style="color:black;" class="custom-file-input" />
                        <label class="custom-file-label"></label>
                    </div>
                    @*@Html.TextBoxFor(model => model.file, "", new { @name= "fileupload", @type = "file" })
                        @Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger" })*@

                </div>

            </div>

            <div class="form-group">
                Product Description
                <div class="col-md-10">
                    <textarea asp-for="Body" name="Desc" type="text">@Model.Rows[0]["P_Desc"].ToString()</textarea>
                    @* @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })*@
                </div>
            </div>

            <div class="form-group">
                Features
                <div class="col-md-10">
                    <textarea type="text" name="Features">@Model.Rows[0]["p_Features"].ToString()</textarea>
                    @*@Html.ValidationMessageFor(model => model.Features, "", new { @class = "text-danger" })*@
                </div>
            </div>

            <div class="form-group">
                Price
                <div class="col-md-10">
                    <input type="text" name="Price" value="@Model.Rows[0]["P_Price"].ToString()" />
                    @*//@Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })*@
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>

INFOMAX/Views/AdminDash/HeaderImage.cshtml
@{
                /**/

                ViewBag.Title = "UploadSliderImage";
                Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/Content/AdminDesign/css/AdminLTE.css" rel="stylesheet" />


<script type="text/javascript">

    $(document).ready(function () {
        $("#dataTable").dataTable();
    });
</script>
<style>
    .row {
        margin-left: 15px;
    }
</style>
<body>
    <!-- Site wrapper -->
    <div class="wrapper" style=" margin-top:-50px;">

        <div class="content-wrapper" style="margin-left:-10px;">
            <!-- Content Header (Page header) -->
            <section class="au-breadcrumb m-t-75">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">

                                <div class="au-breadcrumb-content">
                                    <div class="au-breadcrumb-left"></div>
                                    <button style="margin-left:600px;" class="au-btn au-btn-icon au-btn--green" data-toggle="modal" data-target="#myModal">
                                        <i class="zmdi zmdi-plus"></i>headter images
                                    </button>
                                    <button class="au-btn au-btn-icon au-btn--green" data-toggle="modal" data-target="#myModalPage">
                                        <i class="zmdi zmdi-plus"></i>add pages
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Main content -->
            <section class="content">

                <div class="cols-sm-4 " style="margin-left:20px;">

                    <!-- Default box collapsed-box-->
                    <!--Modal for Header Image-->
                    <div class="modal fade" id="myModal">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Upload New Header Image</h4>
                                    <button type="button" class="close" data-dismiss="modal">×</button>
                                </div>
                                <div class="modal-body">
                                    @using (Html.BeginForm("HeaderImage", "AdminDash", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                    {

                                        <div class="box-body">
                                            <div class="row">

                                                <div class="col-xs-12">

                                                    <div class="form-group">
                                                        <label>Select Page<font color="#C9364D">*</font></label>

                                                        @Html.DropDownList("MenuPage", (SelectList)ViewBag.var1, "Choose Page")

                                                    </div>
                                                    <div class="form-group">
                                                        <label>Header Image (1920x400)<font color="#C9364D">*</font></label><br />
                                                        <input type="file" name="Image" id="Image" class="required" accept="image/*" />
                                                    </div>
                                                </div>


                                            </div>

                                        </div><!-- /.box-body -->
                                        <div class="box-footer">
                                            <input name="bgimage" type="submit" id="bgimage" class="btn btn-primary" value="Update" />
                                        </div><!-- /.box-footer-->

                                    }


                                </div>

                            </div>
                        </div>
                    </div><!-- /.box -->
                    <!--Modal for Adding pages-->

                    <div class="modal fade" id="myModalPage">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Add Page</h4>
                                    <button type="button" class="close" data-dismiss="modal">×</button>
                                </div>
                                <div class="modal-body">
                                    @using (Html.BeginForm("Pages", "AdminDash", FormMethod.Post))
                                    {

                                        <div class="box-body">
                                            <div class="row">

                                                <div class="col-xs-12">

                                                    <div class="form-group">
                                                        <label>Page<font color="#C9364D">*</font></label>

                                                        <input type="text" required name="PageName" class="form-control" />
                                                    </div>

                                                </div>
                                            </div>

                                        </div><!-- /.box-body -->
                                        <div class="box-footer">
                                            <input name="bgimage" type="submit" id="bgimage" class="btn btn-primary" value="Update" />
                                        </div><!-- /.box-footer-->

                                    }


                                </div>

                            </div>
                        </div>
                    </div>



                </div>

                @* <div class="container row">*@

                <!-- Default box collapsed-box-->
                <div class="box box-success">
                    <div class="box-header with-border">
                        <h3 class="box-title">Header Images</h3>
                        <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                        </div>
                    </div>

                    <div class="box-body row">
                        @foreach (var item in Model)
                        {
                            <div class="row-cols-lg-3 m-3">
                                <div class="info-box">
                                    <div class="info-box-content" style="margin:5px;">
                                        <span class="info-box-number" style="height:78px;width:200px;"><img src="@Url.Content(@item.Image)" width="100%" alt="" data-toggle="tooltip" title=@item.Header /></span>

                                        <div class="progress">
                                            <div class="progress-bar" style="width:0%"></div>
                                        </div>
                                        <span class="progress-description">

                                            <span>
                                                @item.Header
                                            </span>
                                        </span>
                                        <div class="col" style="clear:both;"></div>
                                    </div><!-- /.info-box-content -->
                                    <div class="col-1"></div>
                                </div><!-- /.info-box -->
                                <div class="col-4"></div>
                            </div>

                        }

                        <div style="clear:both;"></div>
                    </div><!-- /.box-body -->
                    <!-- /.box-body -->


                </div><!-- /.box -->
                @*  </div>*@




            </section><!-- /.content -->
            <div style="clear:both;"></div>
        </div>
        <script type="text/javascript">
            $(document).ready(function () {
                $("#pages").validate({
                    messages: { page_img: { accept: 'support .jpg' } }
                });
            });
        </script>

        <div class="modal modal-danger fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Are U sure to Delete?</h4>
                    </div>
                    <div class="modal-footer">
                        <button type="button" id="cancel" class="btn btn-outline pull-left" data-dismiss="modal">Cancel</button>
                        <button type="button" id="confirm" class="btn btn-outline">Delete</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->

    </div> <!-- ./wrapper -->
    <!-- SlimScroll -->
    <script src="~/Content/AdminDesign/js/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.11/js/app.min.js" type="text/javascript"></script>

</body>